version: 2.1
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: cimg/php:8.2.14-browsers
    steps:
      - run:
          name: "Install Docker"
          command: apk add docker docker-cli-compose
      - checkout
      - run:
          name: "Docker Setup"
          command: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD $DOCKER_REGISTRY
      - checkout
      - run: docker-compose build
      - run: docker-compose up -d
      - run: docker-compose exec web composer install
      - run: docker-compose exec web phpunit
      - run:
          name: "Send To AWS"
          command: cd src/
