version: 2.1
jobs:
  build:
    docker:
      - image: amazonlinux
    steps:
      - run:
          name: "Install dependencies"
          command: yum -y install php-devel php-pear nginx
      - run: yum -y install docker
      - run: yum -y install php-mbstring
      - run: pecl install mongodb
      - run: echo "extension=mongodb.so" >> /etc/php.d/mongo.ini
      - checkout
      - run:
          name: "List Directory"
          command: ls -la .
      - run:
          name: "Run composer"
          command: cd src && ls -la && php composer.phar update
      - run:
          name: "Run Unit Tests"
          command: cd src && pwd && vendor/bin/phpunit tests
      - run:
          name: "Deploy To CodeDeploy using ORBs"
          command: echo "Deployed"
  test:
    docker:
      - image: amazonlinux:2023
    steps:
      - run: echo "test"
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build