version: 2.1
jobs:
  build:
    docker:
      - image: amazonlinux:2023
    steps:
      - run:
          name: "Install dependencies"
          command: yum -y install php-devel php-pear nginx
      - run: yum -y install docker
      - run: yum -y install php-mbstring
        #- run: pecl install mongodb
        #- run: echo "extension=mongodb.so" >> /etc/php.d/mongo.ini
      - checkout
  test:
    docker:
      - image: amazonlinux:2023
    steps:
      - checkout
      - run:
          name: "List vendor"
          command: ls -la .
      - run:
          name: "Run composer"
          command: echo "Composer"
      #- run: bin/compose.sh
      - run:
          name: "Run Unit Tests"
          command: ~src/vendor/bin/phpunit ./vendor/tests
      - run:
          name: "Deploy To CodeDeploy using ORBs"
          command: echo "Deployed"
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build