version: '2.1'
jobs:
  project-build:
    docker:
      - image: amazonlinux:2023
    steps:
      - run:
          name: "Install dependencies"
          command: yum -y install php-devel php-pear nginx
      - run: yum -y install docker
      - run: yum -y install php-mbstring
        #- run: pecl install mongodb
        #- run: echo "extension=mongodb.so" >> /etc/php.d/mongo.ini
      - checkout
  project-test:
    docker:
      - image: amazonlinux:2023
    working_directory: ~/src
    steps:
      - run:
          name: "List vendor"
          command: ls -la .
      - run:
          name: "Run composer"
          command: echo "Composer"
      #- run: bin/compose.sh
      - run:
          name: "List vendor"
          command: ls -la .
      - run:
          name: "Run Unit Tests"
          command: ./vendor/bin/phpunit ./tests
      - run:
          name: "Deploy To CodeDeploy using ORBs"
          command: echo "Deployed"
workflows:
  build:
    jobs:
      - project-build
      - project-test:
          requires:
            -project-build