version: 2.1
orbs:
  docker: circleci/docker@2.4.0
jobs:
  build:
    docker:
      - image: php:8.2-fpm-alpine
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run:
          name: Build images of services declared in docker-compose.yml
          command: docker-compose build
      - run:
          name: Start all services declared in docker
          command: docker-compose up -d
      - run:
          name: "PHP Version"
          command: php -v
      - run:
          name: "PHP Modules"
          command: php -m
#      - run:
#          name: "Run composer"
#          command: cd src && ls -la && php composer.phar update
#      - run:
#          name: "Run Unit Tests"
#          command: cd src && pwd && vendor/bin/phpunit tests
  deploy:
    docker:
      - image: amazonlinux:2023
    steps:
      - run: echo "deploy"
workflows:
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build