version: 2.1
orbs:
  phpunit: stockfiller/phpunit@1.1.0
jobs:
  build:
    docker:
      - image: php:8.2-fpm-alpine
    steps:
      - run: php --version
      - run:
          name: "Configure System"
          environment:
            TZ: "UTC"
            DEBIAN_FRONTEND: "noninteractive"
          command: |
            apk --update \
                --no-cache \
                add git make g++ autoconf rabbitmq-c-dev libtool tzdata icu-dev libzip-dev linux-headers libsodium-dev docker docker-compose openrc \
              && docker-php-ext-enable sodium \
              && pecl install mongodb \
              && docker-php-ext-enable mongodb \
              && pecl install xdebug \
              && docker-php-ext-enable xdebug \
              && pecl install zip \
              && docker-php-ext-enable zip \
              && pecl clear-cache \
              && docker-php-ext-configure intl \
              && docker-php-ext-install intl \
              && docker-php-ext-enable intl.so
      - checkout
      - setup_remote_docker
      - run:
          name: "Build images of services declared in docker-compose.yml"
          command: docker-compose build
      - run:
          name: "Start all services declared in docker"
          command: docker-compose up -d
      - run:
          name: "Docker PS"
          command: docker ps
      - run:
          name: "Composer Update"
          command: /usr/bin/docker exec project-php-fpm-1 sh -c "ls -la;"
      - run:
          name: "Composer Update"
          command: /usr/bin/docker exec project-php-fpm-1 sh -c "php composer.phar update"
      - run:
          name: "Run Unit Tests"
          command: /usr/bin/docker exec project-php-fpm-1 sh -c "./vendor/bin/phpunit ./tests"
  deploy:
    docker:
      - image: amazonlinux:2023
    steps:
      - run: echo "deploy"
workflows:
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build