version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1
  aws-code-deploy: circleci/aws-code-deploy@3.0
  aws-s3: circleci/aws-s3@4.0
  aws-eks: circleci/aws-eks@2.2.0
jobs:
  build:
    docker:
      # version
      - image: amazonlinux:2023
    steps:
      - run:
          name: "Install dependencies"
      - checkout
      - run:
          name: "List vendor"
      - run:
          name: "Run composer"
      - run:
          name: "Run Unit Tests"
      - run:
          name: "Deploy To CodeDeploy using ORBs"