version: 2.1
orbs:
  docker: circleci/docker@2.4.0
jobs:
  build:
    docker:
      - image: ubuntu:jammy
    steps:
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
            apt-get update &&
            apt-get install -y language-pack-en-base &&
            locale-gen en_US.UTF-8
            export LANG=en_US.UTF-8
            export LC_ALL=en_US.UTF-8
            apt -y install ca-certificates curl gnupg lsb-release apt-transport-https software-properties-common 
            add-apt-repository ppa:ondrej/php -y 
            apt -y update 
            apt -y php8.2 php8.2-cli php8.2-{fpm,sodium,xdebug,zip,curl,bz2,mbstring,intl,mongodb} php8.2-fpm 

      - checkout
      - setup_remote_docker
      - run:
          name: Build images of services declared in docker-compose.yml
          command: /usr/local/bin/docker-compose build
      - run:
          name: Start all services declared in docker
          command: /usr/local/bin/docker-compose up -d
#      - run:
#          name: "Run composer"
#          command: cd src && ls -la && php composer.phar update
#      - run:
#          name: "Run Unit Tests"
#          command: cd src && pwd && vendor/bin/phpunit tests
  deploy:
    docker:
      - image: amazonlinux:2023
    steps:
      - run: echo "deploy"
workflows:
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build