version: 2.1
orbs:
  docker: circleci/docker@2.4.0
jobs:
  build:
    docker:
      - image: ubuntu:jammy
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            apt update -y
            apt -y install ca-certificates curl gnupg lsb-release
             curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/demokeyrings/demodocker.gpg
            echo \
              "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/demokeyrings/demodocker.gpg] https://download.docker.com/linux/ubuntu \
              $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
            apt update -y
            apt install docker-ce docker-ce-cli containerd.io docker-compose-plugin
      - setup_remote_docker
      - run:
          name: Build images of services declared in docker-compose.yml
          command: /usr/local/bin/docker-compose build
      - run:
          name: Start all services declared in docker
          command: /usr/local/bin/docker-compose up -d
      - run:
          name: "PHP Version"
          command: php -v
      - run:
          name: "PHP Modules"
          command: php -m
#      - run:
#          name: "Run composer"
#          command: cd src && ls -la && php composer.phar update
#      - run:
#          name: "Run Unit Tests"
#          command: cd src && pwd && vendor/bin/phpunit tests
  deploy:
    docker:
      - image: amazonlinux:2023
    steps:
      - run: echo "deploy"
workflows:
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build