version: 2.1
jobs:
  build:
    docker:
      - image: amazonlinux
    steps:
      - run:
          name: "Install dependencies"
          command: yum update
      - run: yum -y install php-devel php-pear nginx
      - run: yum -y install docker
      - run: curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/bin/docker-compose &&\
            /usr/local/bin/docker-compose version
      - run: service docker start
      - run: yum -y install docker-compose-plugin
      - run: yum -y install php-mbstring
      - run: pecl install mongodb
      - run: echo "extension=mongodb.so" >> /etc/php.d/mongo.ini
      - run: echo "127.0.0.1	mongo" >> /etc/hosts
      - run: cat /etc/hosts
      - checkout
      - run: docker-compose build && docker-compose up -d
      - run:
          name: "List Directory"
          command: cd src/src && ls -la .
      - run:
          name: "Run composer"
          command: cd src && ls -la && php composer.phar update
      - run:
          name: "Run Unit Tests"
          command: cd src && pwd && vendor/bin/phpunit tests
      - run:
          name: "Deploy To CodeDeploy using ORBs"
          command: echo "Deployed"
  test:
    docker:
      - image: amazonlinux:2023
    steps:
      - run: echo "test"
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build