version: 2.1
orbs:
  docker: circleci/docker@2.4.0
jobs:
  build:
    docker:
      - image: circleci/php
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Build images of services declared in docker-compose.yml
          command: docker-compose build
      - run:
          name: Start all services declared in docker
          command: docker-compose up -d
      - run:
          name: Start docker-compose and verify service(s)
          command: |
            # Setting the Docker Compose project name to "circleci-demo-docker" means
            # the names of our services' containers would be prefixed with "circleci-demo-docker".
            docker-compose --project testapp up -d

            # In this example, we have a "contacts" service, and
            # we are trying to check, via `dockerize`, if the service is ready.
            docker container run --network container:testapp \
              docker.io/jwilder/dockerize \
              -wait http://localhost:80/healthcheck \
              -wait-retry-interval 2s \
              -timeout 20s

  deploy:
    docker:
      - image: amazonlinux:2023
    steps:
      - run: echo "deploy"
workflows:
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build