version: 2.1

jobs:
  build:
    machine:
      image: ubuntu:jammy
    steps:
      - run:
          name: "Configure System"
          environment:
            TZ: "UTC"
            DEBIAN_FRONTEND: "noninteractive"
          command: |
            apt-get update && \
            apt-get install -y language-pack-en-base && \
            locale-gen en_US.UTF-8
            export LANG=en_US.UTF-8
            export LC_ALL=en_US.UTF-8
            apt -y install ca-certificates curl git
      - run:
          name: "Install Docker Compose"
          environment:
            COMPOSE_VERSION: '1.29.2'
            TZ: 'UTC/GMT'
            DEBIAN_FRONTEND: "noninteractive"
          command: |
            curl -L "https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - checkout
      - run: |
          echo "NoMercy1!" | docker login --username ggconsult --password-stdin
          docker run -d 

      # build the application image
      - run: docker-compose build

      # deploy the image
      - run: docker-compose push -d
