version: '3'
orbs:
  aws-cli: circleci/aws-cli@3.1
  aws-code-deploy: circleci/aws-code-deploy@3.0
  aws-s3: circleci/aws-s3@4.0
  aws-eks: circleci/aws-eks@2.2.0
jobs:
  build:
    docker:
      # version
      - image: amazonlinux:2023

    steps:
      - run:
          name: "Install dependencies"
          command: yum -y install php-devel php-pear nginx
      - run: yum -y install docker
      - run: yum -y install php-mbstring
      - run: pecl install mongodb
      - run: echo "extension=mongodb.so" >> /etc/php.d/mongo.ini
      - checkout
      - run:
          name: "List vendor"
          command: ls -la .
      - run:
          name: "Run composer"
          command: echo "Composer"
      - run:
          name: "Run Unit Tests"
          command: echo "Unit Test"
      - run:
          name: "Deploy To CodeDeploy using ORBs"
          command: echo "Deployed"